apiVersion: apps/v1
kind: Deployment
metadata:
    name: firstdeployment
    labels:
        app: nginx
spec:
    replicas: 3
    selector:
        matchLabels:
            app: nginx
    template:
        metadata:
            labels:
                app: nginx
        spec:
            containers:
                - name: firstcontainer
                  image: nginx:latest
