apiVersion: v1
kind: PersistentVolume
metadata:
    name: my-pv-volume
    labels:
        type: local
spec:
    capacity:
        storage: 2Gi
    volumeMode: Filesystem
    accessModes:
        - ReadWriteOnce
    storageClassName: local-storage
    hostPath:
        path: "/tmp/data"
