apiVersion: v1
kind: Service
metadata:
    name: pv-service
spec:
    selector:
        app: pvc-nginx
    type: NodePort
    ports:
        - port: 8080
          targetPort: 80
          nodePort: 32000
