apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: pvc-nginx
    name: pvc-nginx
spec:
    replicas: 2
    selector:
        matchLabels:
            app: pvc-nginx
    template:
        metadata:
            labels:
                app: pvc-nginx
        spec:
            containers:
                - image: nginx:latest
                  name: nginx
                  resources:
                      limits:
                          memory: "256Mi"
                          cpu: "500m"
                  ports:
                      - containerPort: 80
                        name: "http-server"
                  volumeMounts:
                      - name: pv-storage
                        mountPath: /usr/share/nginx/html
            volumes:
                - name: pv-storage
                  persistentVolumeClaim:
                      claimName: pv-claim
