apiVersion: v1
kind: ReplicationController
metadata:
  name: firstrc
  labels:
    name: firstrc 
spec:
  replicas: 2
  selector:
    app: myapp
  template:
    metadata:
      name: firstpod
      labels:
        app: myapp
    spec:
      containers:
        - name: firstcontainer
          image: nginx:latest
          ports:
            - containerPort: 80
