apiVersion: v1
kind: Pod
metadata:
  name: pod4
  labels:
    app: myapp4
    type: backend
spec:
  containers:
  - name: myapp1-container
    image: nginx:latest
    ports:
    - containerPort:  80
      name:  http