apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    app: myapp
    type: frontend
spec:
  containers:
  - name: myapp-container
    image: nginx:latest
    ports:
    - containerPort:  80
      name:  http