apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: thirdrs
  labels:
    app: thirdrs
spec:
  # modify replicas according to your case
  replicas: 4
  selector:
    matchExpressions:
    - key : app
      operator: In
      values:
        - myapp
        - myapp1
    - key : type
      operator: NotIn
      values:
        - backend
  template:
    metadata:
      labels:
        app: myapp1
    spec:
      containers:
        - name: firstcontainer
          image: nginx:latest
          ports:
            - containerPort: 80
