apiVersion: v1
kind: Pod
metadata:
  name: pod3
  labels:
    app: myapp3
    type: frontend
spec:
  containers:
  - name: myapp1-container
    image: nginx:latest
    ports:
    - containerPort:  80
      name:  http