apiVersion: v1
kind: Pod
metadata:
    name: init-container-demo
    labels:
        app: init-container-demo
spec:
    initContainers:
        - name: init-myservice
          image: busybox:latest
          command: ["sh", "-c", 'echo "Initializing..." && echo "Hello from Init Container" > /app/index.html']
          volumeMounts:
              - name: shared-data
                mountPath: /app

    containers:
        - name: nginx
          image: nginx:latest
          ports:
              - containerPort: 80
          volumeMounts:
              - name: shared-data
                mountPath: /usr/share/nginx/html

    volumes:
        - name: shared-data
          emptyDir: {}
