apiVersion: v1
kind: Pod
metadata:
    name: multi-container-pod
    labels:
        app: multi-container
spec:
    containers:
        - name: nginx-container
          image: nginx:latest
          ports:
              - containerPort: 80 # Nginx will listen on port 80
          env:
              - name: firstname
                value: Vishal
              - name: lastname
                value: Meshram

        - name: busybox-container
          image: busybox:latest
          command: ["sh", "-c", "echo 'Hello from busybox!' && sleep 3600"] # Run a simple command and keep the container alive
          env:
              - name: City
                value: Pune
