apiVersion: v1
kind: Pod
metadata:
    name: test-nginx-pod
    labels:
        name: test-nginx-pod
spec:
    containers:
        - name: test-nginx-pod
          image: nginx:latest
          resources:
              limits:
                  memory: "256Mi"
                  cpu: "500m"
          ports:
              - containerPort: 80
