apiVersion: v1
kind: ReplicationController
metadata:
    name: firstrc
    labels:
        app: nginx
spec:
    replicas: 1
    template:
        metadata:
            name: firstpod
            labels:
                app: nginx
        spec:
            containers:
                - name: firstcontainer
                  image: nginx:latest
