apiVersion: v1
kind: ReplicationController
metadata:
    name: secondrc
spec:
    replicas: 1
    selector:
        app: nginx
    template:
        metadata:
            name: secondpod
            labels:
                app: nginx
        spec:
            containers:
                - name: secondcontainer
                  image: nginx:latest
                  ports:
                      - containerPort: 80
