apiVersion: apps/v1
kind: Deployment
metadata:
    name: firstdeployment
    labels:
        app: nginx
spec:
    replicas: 5
    selector:
        matchLabels:
            app: nginx
    template:
        metadata:
            name: dpod
            labels:
                app: nginx
        spec:
            containers:
                - name: container
                  image: nginx:latest
                  ports:
                      - containerPort: 80
                  resources:
                      limits:
                          cpu: 500m
                          memory: 512Mi
---
# Service for the above deployment

apiVersion: v1
kind: Service
metadata:
    name: firstservice
    labels:
        app: nginx
spec:
    type: NodePort
    selector:
        app: nginx
    ports:
        - port: 80
          targetPort: 80
          nodePort: 32000
