apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: my-deployment
    name: my-deployment
spec:
    replicas: 3
    selector:
        matchLabels:
            app: my-deployment
    strategy:
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
    template:
        metadata:
            labels:
                app: my-deployment
        spec:
            containers:
                - image: nginx:1.27
                  imagePullPolicy: IfNotPresent
                  name: my-nginx-container
                  
